/D/VulkanSDK/1.1.106.0/Bin32/glslangValidator.exe -V test.vert -o test.vert.spv
/D/VulkanSDK/1.1.106.0/Bin32/glslangValidator.exe -V test.frag -o test.frag.spv
/D/VulkanSDK/1.1.106.0/Bin32/glslangValidator.exe -V characters.frag -o characters.frag.spv
/D/VulkanSDK/1.1.106.0/Bin32/glslangValidator.exe -V fullscreen.vert -o fullscreen.vert.spv
/D/VulkanSDK/1.1.106.0/Bin32/glslangValidator.exe -V fullscreen.frag -o fullscreen.frag.spv
/D/VulkanSDK/1.1.106.0/Bin32/glslangValidator.exe -V uioverlay.vert -o uioverlay.vert.spv
/D/VulkanSDK/1.1.106.0/Bin32/glslangValidator.exe -V uioverlay.frag -o uioverlay.frag.spv
/D/VulkanSDK/1.1.106.0/Bin32/glslangValidator.exe -V shatter.vert -o shatter.vert.spv
/D/VulkanSDK/1.1.106.0/Bin32/glslangValidator.exe -V shatter.frag -o shatter.frag.spv
